apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.services.mosip_file_server.podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  minReadySeconds: {{ .Values.services.mosip_file_server.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.mosip_file_server.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.mosip_file_server.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: {{ .Values.docker.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "mkdir -p {{ .Values.well_known_path }} {{ .Values.mobileapp_path }} && cp {{ .Values.mountPath }}/.well-known/mosipvc/* {{ .Values.well_known_path }} && /bin/bash  /home/mosip/get-cert.sh && echo 'starting nginx'&& nginx && sleep infinity;"]
          env:
            - name: spring_config_label_env
              value: {{ .Values.springConfigLabel }}
            - name: spring_config_url_env
              value: {{ .Values.configServerUrl }}
            - name: AUTHMANAGER_URL
              value: {{ .Values.authmanagerUrl }}
            - name: KEYMANAGER_URL
              value: {{ .Values.keymanagerUrl }}
            - name: active_profile_env
              value: {{ .Values.activeProfileEnv }}
            - name: MOSIP_REGPROC_CLIENT_SECRET
              value: {{ .Values.mosip_regproc_client_secret }}
          ports:
            - containerPort: {{ .Values.docker.ports.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.services.mosip_file_server.healthUrl }}
              port: {{ .Values.docker.ports.containerPort }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
            periodSeconds: {{ .Values.probe.period }}
            timeoutSeconds: {{ .Values.probe.timeout }}
          livenessProbe:
            httpGet:
              path: {{ .Values.services.mosip_file_server.healthUrl }}
              port: {{ .Values.docker.ports.containerPort }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
            periodSeconds: {{ .Values.probe.livenessPeriod }}
            timeoutSeconds: {{ .Values.probe.timeout }}
          startupProbe:
            httpGet:
              path: {{ .Values.services.mosip_file_server.healthUrl }}
              port: {{ .Values.docker.ports.containerPort }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
            periodSeconds: {{ .Values.probe.startupPeriod }}
            timeoutSeconds: {{ .Values.probe.timeout }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}

          volumeMounts:
            - name: mosip-file-server-volume
              mountPath: {{ .Values.mountPath }}
      volumes:
        - name: mosip-file-server-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}                                                                                                        

