apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.captcha.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.services.captcha.ports.servicePort }}
    targetPort: {{ .Values.services.captcha.ports.containerPort }}
  selector:
    app: {{ .Values.services.captcha.serviceName }}
