apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.digitalcard.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.digitalcard.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: {{ .Values.services.digitalcard.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.services.digitalcard.serviceName }} 
  minReadySeconds: {{ .Values.services.digitalcard.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.digitalcard.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.digitalcard.podconfig.maxSurge }}
  template:
    metadata:
      annotations:
        prometheus.io/path: {{ .Values.services.digitalcard.annotation }}
        prometheus.io/port: {{ .Values.services.digitalcard.ports.containerPort | quote }}
        prometheus.io/scrape: "'true'"
      labels:
        app: {{ .Values.services.digitalcard.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.digitalcard.serviceName }} 
        image: {{ .Values.services.digitalcard.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{ $resources := .Values.services.digitalcard.podconfig.resources }}
        {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        ports:
        - containerPort: {{ .Values.services.digitalcard.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.digitalcard.healthUrl }}
            port: {{ .Values.services.digitalcard.ports.containerPort }}
          periodSeconds: {{ .Values.probe.period }}
          timeoutSeconds: {{ .Values.probe.timeout }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.digitalcard.healthUrl }}
            port: {{ .Values.services.digitalcard.ports.containerPort }}
          periodSeconds: {{ .Values.probe.livenessPeriod }}
          timeoutSeconds: {{ .Values.probe.timeout }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
        startupProbe:
          httpGet:
            path: {{ .Values.services.digitalcard.healthUrl }}
            port: {{ .Values.services.digitalcard.ports.containerPort }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
          periodSeconds: {{ .Values.probe.startupPeriod }}
          timeoutSeconds: {{ .Values.probe.timeout }}
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}

